# Generated by Django 3.0 on 2019-12-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_auto_20191206_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership_tier',
        ),
    ]
