# Generated by Django 3.0 on 2019-12-08 13:03

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gymapp', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], max_length=4)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('membership_tier', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], default='B', max_length=1)),
            ],
        ),
    ]
