# Generated by Django 3.0 on 2019-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_gymmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='title',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('miss', 'Miss'), ('dr', 'Dr')], max_length=4),
        ),
    ]
