# Generated by Django 3.0 on 2019-12-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_auto_20191216_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
