# Generated by Django 3.0.1 on 2019-12-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_gymclasssession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(choices=[('spin', 'Spinning'), ('bxng', 'Boxing'), ('LBT', 'Legs bums & tums')], max_length=4)),
                ('class_description', models.CharField(max_length=200)),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GymTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('miss', 'Miss'), ('dr', 'Dr')], max_length=4)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='GymClassSession',
        ),
        migrations.AddField(
            model_name='gymclasses',
            name='class_instructor',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='gymapp.GymTrainer'),
        ),
    ]
