# Generated by Django 3.0.1 on 2019-12-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_auto_20191218_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='membership_tier',
            field=models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], default='B', max_length=7),
        ),
    ]
