# Generated by Django 3.0.1 on 2019-12-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_auto_20191219_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7),
        ),
    ]
